version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  notification-service: 
    build:
      context: .
    image: notification-service:latest
    container_name: notification-service
    environment:
      - PORT=3000
      - API_KEY=mySup3rAp!K3y
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - MONGO_HOST=mongo
    ports:
      - 3000:3000


